### ISSUE TITLE
Handle optional Geocoding fields in response

### ISSUE THREAD

**Issue by royjoshu** [leontoeides/google_maps#12]
I use the Google Maps Javascript API, and can select which fields I get in response.

I'm having an issue where Google's JS library returns a different type of `viewport` -- `north`, `east`, `west`, `south` -- instead of `southwest`, `northeast`, when using the Autocomplete API.

Two options to solve this:
1. Make `viewport` an `Option` and not request it through the API.
2. Make it an `enum` to support both formats.

Would be happy to create a PR, do you have a preference to 1 or 2?

References:
https://developers.google.com/maps/documentation/javascript/reference/places-service#PlaceResult
https://developers.google.com/maps/documentation/javascript/reference/coordinates#LatLngBounds

**Comment by leontoeides** [comment]
Sorry I missed your issue. I will respond shortly

**Comment by leontoeides** [comment]
I was thinking about this and in my opinion, this is out-of-scope. It looks like Google have made a bit of a mess of things. Maybe you could fork this `google_maps` crate and republish a JS-version?

**Comment by royjoshu** [comment]
Thank you very much for your response,
Meanwhile I found a workaround, I'll figure it out soon.
Roy Glick
