### ISSUE TITLE
Feature Request - nearby_search

### ISSUE THREAD

**Issue by ethanwc** [leontoeides/google_maps#17]
Hi I would like to use some existing functionality that is mapped here, as well as google's `nearby_search` request. Would you be interested in implementing this functionality, otherwise providing some high level steps on how to add support.

I don't see a great example PR towards adding a new function, if you'd like me to take a stab at this, could you point me to some specific commits.

Thanks.

**Comment by ethanwc** [comment]
Glancing through the repo I am guessing I would need to:

1. define `nearby_search` in `impls.rs` with a test
2. stub out boiler plate towards similar request building pattern
3. add a lot of http status maping logic in new `get.rs` file

**Comment by leontoeides** [comment]
Hello ethanwc. Sorry for the delayed response.

There is an unfortunate amount of boiler-plate, especially surrounding the `get` functions. Converting to generics would be a bit of a project but wouldn't benefit the end-user or resulting binary, so I haven't bothered yet.

Thank you for your kind offer, but don't worry about this. I will work on this during the weekend. It looks like a lot of the necessary structs are already made.

**Comment by leontoeides** [comment]
Hey there, a new version of the crate has been published. Let me know if you run into any problems. Good luck with your project!

**Comment by ethanwc** [comment]
Works as expected, thanks!
