### ISSUE TITLE
Add landmark to place type

### ISSUE THREAD

**Issue by oknozor** [leontoeides/google_maps#21]
Currently getting the following error: 
```
called `Result::unwrap()` on an `Err` value: Google Maps Platform API client: `landmark` is not a recognized place type code. For a list of supported place types see https://developers.google.com/places/web-service/supported_types at line 67892 column 10
```

 while `landmark` is showing up in the documentation.

**Comment by leontoeides** [comment]
Sorry for the delay. `Landmark` has been added in a newly published v3.4.1.

If there are any other issues please let me know. Now that my computer is up-and-running and I'll try to address them faster.
