### ISSUE TITLE
`Result::unwrap()` on an `Err` value: Google Maps Directions API client in the Serde JSON library: missing field `html_instructions`

### ISSUE THREAD

**Issue by azerpas** [leontoeides/google_maps#23]
## Code

```rs
// self.address = "Regensburger Str. 35 93180 Deuerling".to_string()

let api_key = std::env::var("MAPS_API_KEY")?;
let google_maps_client = GoogleMapsClient::new(&api_key);

let transit_directions = google_maps_client.directions(
    Location::LatLng(LatLng::try_from_f64(48.8525837, 2.3723538)?),
    Location::Address(self.address.clone()),
)
    .with_travel_mode(TravelMode::Transit)
    .execute()
    .await?;
 ```

## Error
```
called `Result::unwrap()` on an `Err` value: Google Maps Directions API client in the Serde JSON library: missing field `html_instructions` at line 447 column 25
```

Replacing 
https://github.com/leontoeides/google_maps/blob/1afac5de3630986c5e5acdc760e09e6ea473202f/src/directions/response/step.rs#L46
by 
```rs
pub html_instructions: Option<String>,
```
fixes it

It's weird cause I've intercepted the request and it seems that each `html_instructions` field is defined.

**Comment by leontoeides** [comment]
Thanks for reporting this and thank you for the pull request. Much appreciated

I'm a bit (but not completely) surprised by this. If possible, could you try updating your dependencies and running `cargo update` to see if that helps? 

If that doesn't help, I will merge your PR.

Also note that I'm waiting for a dependency to update. Once that happens, if need be, I'll publish this change with v3.5.0.

**Comment by azerpas** [comment]
> Thanks for reporting this and thank you for the pull request. Much appreciated
> 
> I'm a bit (but not completely) surprised by this. If possible, could you try updating your dependencies by running `cargo update` to see if that helps?
> 
> If that doesn't help, I will merge your PR.
> 
> Also note that I'm waiting for a dependency to update. Once that happens, if need be, I'll publish this change with v3.5.0.

No problem! 

I'm still getting the same error after update all of the dependencies. 

Let me know if you want me to send you more logs.

**Comment by leontoeides** [comment]
Thanks a bunch! I've merged this. I'm trying to hold-out for a dependency update. I hope that your fix will be published soon
