### ISSUE TITLE
native-tls included in dependencies even with rustls enabled

### ISSUE THREAD

**Issue by seanpianka** [leontoeides/google_maps#25]
Hello 👋 

I upgraded from 2.x to 3.x and saw that native-tls features for reqwest are included in the build, even when the rustls feature is specified for the google_maps crate. It would seem that this new dependency for reqwest-maybe-middleware causes this. I don't know much about this project, but considering it has no README, no stars, and seems to be relatively inactive, it may be best to just include its source code into the project (or fork it, publish your own version, and maintain it separately).

Additionally, it would be helpful to upgrade reqwest to 0.12 from 0.11.

Thanks!

**Comment by leontoeides** [comment]
Good afternoon Sean 👋 I was holding out for an update on `reqwest-maybe-middleware`. I was thinking the same thing - if we don't have an update by next weekend I'll just fork it. It's very small. Also, great catch on the `reqwest` features being pulled in through that crate.

Thanks again for your feedback and advice. I really appreciate it!

**Comment by seanpianka** [comment]
Happy to help. It looks like the newest release of that crate is available now.

**Comment by leontoeides** [comment]
Good morning Sean. I just published `3.5.0` and I forgot to check into this issue before I published. How are things looking on your end?

**Comment by leontoeides** [comment]
I think your issue has been addressed. Feel free to open again if it hasn't
