### ISSUE TITLE
Cannot be used in async context, conflicts with parent runtime

### ISSUE THREAD

**Issue by ysangkok** [leontoeides/google_maps#3]
I am using this library from an async context, and it seems to break with the message:

> thread 'tokio-runtime-worker' panicked at 'Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.'

I have worked around it using an additional thread to wrap the google_maps usage.

But really, shouldn't the library be modified to be able to be used in a context with an existing runtime?

I was thinking, maybe it would be possible to provide either an async API? Alternatively, google_maps could simply return a reqwest::RequestBuilder and let me execute the request with my own reqwest::Client, then I could pass the response back into this library.

Or maybe there is some other obvious solution I am missing?

Thanks for your efforts, it works fine so far!

**Comment by victorct-pronto** [comment]
Having the same problem here.

**Comment by leontoeides** [comment]
Thanks for the feedback and sharing your workaround.

I haven't done any async work in Rust yet so it's more likely I'm missing something than you. The library is really just a glorified library of structs so maybe it has something to do with using the blocking version of Reqwest?

I like your idea of having the option to execute your own HTTP GET request and sending back the results. I'm not a big fan of having Reqwest as a dependency. 

It might be a week or two before I can look at this more closely.

**Comment by yandexx** [comment]
FYI I've encountered the same issue when using blocking Reqwest client, independently of google_maps. Might be an issue in Reqwest or tokio, which I intend to minimize and report.

**Comment by headuck** [comment]
I had this issue before, and had created an async fork of this project for my own use [here](https://github.com/headuck/google_maps). You may take reference from the approach.

**Comment by Mause** [comment]
@headuck do you have any plans to update it for tokio 1?

**Comment by headuck** [comment]
My fork is being used in a 0.2 environment with other crates which also depends on 0.2. Perhaps need to wait a little bit when the dependencies are updated.

**Comment by Mause** [comment]
@headuck no worries, I wound up using the compatibility crate and it worked with no issues
