### ISSUE TITLE
Issue EitherRestrictionsOrWaypoints fires in opposite case

### ISSUE THREAD

**Issue by ARBaart** [leontoeides/google_maps#32]
It currently fires when
```rust
        // If waypoints have been set...
        if !self.waypoints.is_empty() {
            // ...
            // ...restrictions cannot be set:
            if self.restrictions.is_empty() {
```

This should presumably be if restrictions are _not_ empty. I'll create a PR, always wanted to make one with one character!

**Comment by leontoeides** [comment]
Thank you for sending this @ARBaart! I've published the update
