### ISSUE TITLE
Switch from `log` to `tracing`

### ISSUE THREAD

**Issue by seanpianka** [leontoeides/google_maps#7]
We currently use log for logging, but we also pull in tracing through Hyper, and the nesting structure of tracing might be a good fit for us anyway. So, we should switch to tracing everywhere.

**Proposal**

- Replace all uses of the log crate with tracing (there are verbatim replacements for the logging macros, so no code changes)
- Replace all uses of {:?} in tracing macro invocations with ?value infront of the format string

**Comment by leontoeides** [comment]
That's a good idea. I think I will do this through a feature flag maybe?

**Comment by seanpianka** [comment]
I think it would be fine to migrate entirely away from log in the crate's implementation, and enable certain `log` compatibility features within `tracing` to enable backwards compatibility in existing `2.0.0` users.

See this section on [_migrating from `log` to `tracing`_](https://www.lpalmieri.com/posts/2020-09-27-zero-to-production-4-are-we-observable-yet/#5-2-migrating-from-log-to-tracing) for an idea of what the migration might look like.

**Comment by leontoeides** [comment]
Very cool! Look at all of these newfangled things you're introducing me to. Thank you! I've merged your request, added support for tracing, tested it, and published the crate.
